
server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: pass
      database: wishlist_db

wishlist:
  page-max-size: 20
