swagger: "2.0"
info:
  title: Wishlist API
  description: API for manage user wishlist.
  version: 1.0.0

host: blablabla.com
basePath: /api/v1
schemes:
  - https

paths:
  /wishlist:
    post:
      summary: Save one product to client wishlist.
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Product client to save in wishlist"
          required: true
          schema:
            $ref: "#/definitions/WishlistRequest"
      responses:
        201:
          description: Created

  /wishlist/product/{productId}:
    delete:
      summary: Delete specific product from client wishlist.
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: "Client identifier"
          required: true
          schema:
            $ref: "#/definitions/Client"
        - in: path
          name: productId
          description: Product ID
          required: true
          type: string
      responses:
        200:
          description: Ok Product Deleted

definitions:
  WishlistRequest:
    type: object
    properties:
      client:
        type: string
      product:
        type: object
        items:
          $ref: '#/definitions/Product'

  Client:
    type: object
    properties:
      client:
        type: string

  Product:
    type: object
    properties:
      id:
        type: string
