swagger: "2.0"
info:
  title: Wishlist API
  description: API for manage user wishlist.
  version: 1.0.0

host: blablabla.com
basePath: /api/v1/wishlist
schemes:
  - https

paths:
  /:
    post:
      summary: Save one product to client wishlist.
      produces:
        - application/json
      parameters:
        - in: body
          name: "body"
          description: "Product client to save in wishlist"
          required: true
          schema:
            $ref: "#/definitions/WishlistRequest"
        - in: header
          name: client
          description: "client identifier"
          type: string
          required: true

      responses:
        201:
          description: Created

  /products:
    get:
      summary: Get client products wishlist.
      produces:
        - application/json
      parameters:
        - in: query
          type: integer
          name: page
          description: "Products client number page request"
        - in: header
          name: client
          description: "client identifier"
          type: string
          required: true

      responses:
        200:
          description: OK
          schema:
            items:
              $ref: "#/definitions/PagedProductResponse"

  /products/{productId}:
    delete:
      summary: Delete specific product from client wishlist.
      produces:
        - application/json
      parameters:
        - in: header
          name: client
          description: "client identifier"
          type: string
          required: true
        - in: path
          name: productId
          description: Product ID
          required: true
          type: string

      responses:
        200:
          description: Ok Product Deleted

definitions:
  WishlistRequest:
    type: object
    properties:
      product:
        type: object
        items:
          $ref: '#/definitions/Product'

  Product:
    type: object
    properties:
      id:
        type: string

  PagedProductResponse:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: '#/definitions/Product'
      currentPage:
        type: integer
      totalPageItems:
        type: integer
      lastPage:
        type: boolean
